### ISSUE TITLE
test is not defined.

### ISSUE THREAD

**Issue by jcarasick-geog8r** [lerna/getting-started-example#13] opened 2022-09-22 18:56 UTC
working through the getting started and getting this on lerna run start (or dev). lerna run test works though. am i missing something?

test('example spec', () => {
^
ReferenceError: test is not defined
    at Object.<anonymous> (C:\LocalProj\Development\<user>\lerna-sample\packages\remixapp\app\routes\example.spec.tsx:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\LocalProj\Development\<user>\lerna-sample\node_modules\@remix-run\serve\dist\cli.js:48:13)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
npm ERR! Lifecycle script `start` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: remixapp
npm ERR!   at location: C:\LocalProj\Development\<user>\lerna-sample\packages\remixapp

**Comment by juristr** [comment] 2022-10-26 12:12
duplicate of #2. This will be addressed shortly. Thanks for letting us know :)

**Closed by juristr** 2022-10-26 12:12 UTC
