### ISSUE TITLE
[ERROR] could not build header and footer 

### ISSUE THREAD

**Issue by shivamsinghcse** [lerna/getting-started-example#28] opened 2023-07-14 08:27 UTC
when run command `npx lerna run build` 
got the output
> ```
 Lerna (powered by Nx)   Ran target build for 3 projects (2s)
 
    ✔    0/2 succeeded [0 read from cache]
 
    ✖    2/2 targets failed, including the following:
         - header:build
         - footer:build
```

**Comment by fahslaj** [comment] 2023-08-22 14:41
Hi @shivamsinghcse , I am closing this issue as I cannot reproduce the issue and it is lacking context. Feel free to follow up if you are still experiencing this problem.

**Closed by fahslaj** 2023-08-22 14:41 UTC
